// Textes d'interface non éditables dans la page (formulaire de réservation,
// libellés d'accessibilité…). Le contenu du site lui-même est traduit via un
// document par langue ; ceci ne couvre que les chaînes codées en dur.
const STRINGS = {
  fr: {
    service: 'Service',
    date: 'Date',
    time: 'Heure',
    loadingSlots: 'Chargement des créneaux…',
    noSlots: 'Aucun créneau disponible ce jour — essayez une autre date.',
    fullName: 'Nom complet',
    namePlaceholder: 'Votre nom',
    emailOptional: 'E-mail (facultatif)',
    whatsapp: 'WhatsApp',
    socialPage: 'Page Facebook ou Instagram',
    socialHint: 'Le lien de votre page à promouvoir — obligatoire.',
    budget: 'Budget marketing (facultatif)',
    budgetNone: '— Non précisé —',
    domain: "Domaine d'activité",
    domainOther: 'Précisez votre domaine',
    domainOtherPlaceholder: 'Ex. agence de voyage',
    message: 'Message (facultatif)',
    messagePlaceholder: 'Précisez votre besoin…',
    genericError: 'Une erreur est survenue',
    prev: 'Précédent',
    next: 'Suivant',
    backToTop: 'Retour en haut de page',
    mainNav: 'Navigation principale',
    menu: 'Menu',
    language: 'Langue',
    admin: 'Administration',
  },
  ar: {
    service: 'الخدمة',
    date: 'التاريخ',
    time: 'الوقت',
    loadingSlots: 'جارٍ تحميل المواعيد…',
    noSlots: 'لا توجد مواعيد متاحة في هذا اليوم — جرّب تاريخًا آخر.',
    fullName: 'الاسم الكامل',
    namePlaceholder: 'اسمك',
    emailOptional: 'البريد الإلكتروني (اختياري)',
    whatsapp: 'واتساب',
    socialPage: 'صفحة فيسبوك أو إنستغرام',
    socialHint: 'رابط صفحتك التي تريد الترويج لها — إجباري.',
    budget: 'ميزانية التسويق (اختياري)',
    budgetNone: '— غير محدد —',
    domain: 'مجال النشاط',
    domainOther: 'حدّد مجالك',
    domainOtherPlaceholder: 'مثال: وكالة أسفار',
    message: 'رسالة (اختياري)',
    messagePlaceholder: 'وضّح احتياجك…',
    genericError: 'حدث خطأ ما',
    prev: 'السابق',
    next: 'التالي',
    backToTop: 'العودة إلى الأعلى',
    mainNav: 'التنقل الرئيسي',
    menu: 'القائمة',
    language: 'اللغة',
    admin: 'الإدارة',
  },
  en: {
    service: 'Service',
    date: 'Date',
    time: 'Time',
    loadingSlots: 'Loading time slots…',
    noSlots: 'No slot available that day — try another date.',
    fullName: 'Full name',
    namePlaceholder: 'Your name',
    emailOptional: 'E-mail (optional)',
    whatsapp: 'WhatsApp',
    socialPage: 'Facebook or Instagram page',
    socialHint: 'The link of the page to promote — required.',
    budget: 'Marketing budget (optional)',
    budgetNone: '— Not specified —',
    domain: 'Business sector',
    domainOther: 'Specify your sector',
    domainOtherPlaceholder: 'E.g. travel agency',
    message: 'Message (optional)',
    messagePlaceholder: 'Describe your need…',
    genericError: 'Something went wrong',
    prev: 'Previous',
    next: 'Next',
    backToTop: 'Back to top',
    mainNav: 'Main navigation',
    menu: 'Menu',
    language: 'Language',
    admin: 'Admin',
  },
} as const;

export type UiStrings = Record<keyof (typeof STRINGS)['fr'], string>;

/** Dictionnaire d'une langue ; langue inconnue → français. */
export function uiStrings(locale: string): UiStrings {
  return (STRINGS as unknown as Record<string, UiStrings>)[locale] ?? STRINGS.fr;
}
